apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "1s"
      queryTimeout: "60s"

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      host: clickhouse
      port: 8123
      username: drift
      defaultDatabase: drift
      protocol: http
    secureJsonData:
      password: $CLICKHOUSE_PASSWORD
    editable: false
