services:
  drift-monitor:
    build:
      context: ../.. # Build from root of unshred repo
      dockerfile: examples/drift-monitor/Dockerfile
    image: drift-monitor:latest
    container_name: drift-monitor
    ports:
      - "127.0.0.1:9090:9090" # Metrics
      - "0.0.0.0:8001:8001/udp"
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_URL=${CLICKHOUSE_URL}
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    networks:
      - drift-net
    restart: unless-stopped
    depends_on:
      clickhouse:
        condition: service_healthy

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: drift-clickhouse
    ports: []
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./migrations/clickhouse:/docker-entrypoint-initdb.d # Auto-run the migrations on first start
    networks:
      - drift-net
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 30s
      timeout: 3s
      retries: 5
    env_file:
      - .env
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: drift-prometheus
    ports: []
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=${PROMETHEUS_RETENTION:-7d}"
      - "--storage.tsdb.retention.size=${PROMETHEUS_MAX_SIZE:-5GB}"
      - "--storage.tsdb.wal-compression"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    networks:
      - drift-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: drift-grafana
    ports:
      - "0.0.0.0:3000:3000" # Dashboard access
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      - GF_AUTH_BASIC_ENABLED=true
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_SNAPSHOTS_EXTERNAL_ENABLED=false
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    networks:
      - drift-net
    depends_on:
      - prometheus
      - clickhouse
    restart: unless-stopped

volumes:
  clickhouse_data:
  prometheus_data:
  grafana_data:

networks:
  drift-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
